### ISSUE TITLE
v0.7/1.0 compatability

### ISSUE THREAD

**Issue by ZacLN** [ZacLN/CSTParser.jl#64]
- [ ] #22089: suffixed operators (Tokenize)
- [ ] #24404: add operator (Tokenize)
- [ ]  introduce specific literal types for bin/hex/oct (Tokenize)
- [ ] #16356: disallow juxtaposition of bin/hex/octs
- [ ] #24153: make `<|` right associative
- [ ] #8470: replace `cell1d` and `cell2d` expr heads w/ `braces` and `bracescat` respectively
- [ ]  #21774: replace `if` head w/ `elseif` in `elseif` blocks
- [ ] #21774: collect `let` assignments as in `for` blocks`
- [ ] #21774: add `:do` head
- [ ] #23157: rename datatype heads
- [ ] #25391: add higher precedence for `=>`
- [x] #20575: disallow string literals juxtaposed (trailed) by a symbol
- [ ] #18650: change handling of macro calls to arguments of generators/comprehensions
- [ ] #16937: parse error on repeated argument names (implement?)
- [x] #22868: disallow `@ macroname args` (space)
- [x] #22868: disallow juxtaposition of symbol w/ macrocall (was already disallowed)
- [x] use `GenericIOBuffer`
- [x] use `@nospecialize`
